### ISSUE TITLE
Build fail: Value 65536 is out-of-range

### ISSUE THREAD

**Issue by denizzzka** [toby1984/jASM_16#7]
```
$ mvn install
[ some thousands of lines]
	at org.apache.maven.surefire.booter.SurefireBooter.main(SurefireBooter.java:1009)
----------------- before compilation of string resource (string input) (has_errors=false] -----------------
----------------- before compilation of string resource (string input) (has_errors=false] -----------------
----------------- before compilation of string resource (string input) (has_errors=false] -----------------
----------------- before compilation of string resource (string input) (has_errors=false] -----------------
----------------- before compilation of string resource (string input) (has_errors=false] -----------------
----------------- before compilation of string resource (string input) (has_errors=false] -----------------
----------------- before compilation of string resource (string input) (has_errors=false] -----------------
----------------- before compilation of string resource (string input) (has_errors=false] -----------------
----------------- before compilation of string resource (string input) (has_errors=false] -----------------
----------------- before compilation of string resource (string input) (has_errors=false] -----------------
----------------- before compilation of string resource (string input) (has_errors=false] -----------------
----------------- before compilation of string resource (string input) (has_errors=false] -----------------
----------------- before compilation of string resource (string input) (has_errors=false] -----------------
ERROR: line 1, column 13: label: .dat label+0xffff+1
                                      ^ Value 65536 is out-of-range
ERROR: line 1, column 13: label: .dat label+0xffff+1
                                      ^ Value 65536 is out-of-range
----------------- before compilation of string resource (string input) (has_errors=false] -----------------
----------------- before compilation of string resource (string input) (has_errors=false] -----------------
----------------- before compilation of string resource (string input) (has_errors=false] -----------------
----------------- before compilation of string resource (string input) (has_errors=false] -----------------
----------------- before compilation of string resource (string input) (has_errors=false] -----------------
----------------- before compilation of string resource (string input) (has_errors=false] -----------------
----------------- before compilation of string resource (string input) (has_errors=false] -----------------
----------------- before compilation of string resource (string input) (has_errors=false] -----------------
----------------- before compilation of string resource (string input) (has_errors=false] -----------------
----------------- before compilation of string resource (string input) (has_errors=false] -----------------
----------------- before compilation of string resource (string input) (has_errors=false] -----------------
----------------- before compilation of string resource (string input) (has_errors=false] -----------------
----------------- before compilation of string resource (string input) (has_errors=false] -----------------
----------------- before compilation of string resource (string input) (has_errors=false] -----------------
----------------- before compilation of string resource (string input) (has_errors=false] -----------------
----------------- before compilation of string resource (string input) (has_errors=false] -----------------

-----
AST Node LabelNode has no text region set----------------- before compilation of string resource (dummy) (has_errors=false] -----------------
java.lang.RuntimeException: Internal error, encountered local label label without any previous global label ?
	at de.codesourcery.jasm16.ast.LabelNode.parseInternal(LabelNode.java:122)
	at de.codesourcery.jasm16.ast.ASTNode.parse(ASTNode.java:717)
	at de.codesourcery.jasm16.parser.LabelNodeTest.testParseLocalLabelWithoutPreviousGlobalFirst(LabelNodeTest.java:39)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at junit.framework.TestCase.runTest(TestCase.java:168)
	at junit.framework.TestCase.runBare(TestCase.java:134)
	at junit.framework.TestResult$1.protect(TestResult.java:110)
	at junit.framework.TestResult.runProtected(TestResult.java:128)
	at junit.framework.TestResult.run(TestResult.java:113)
	at junit.framework.TestCase.run(TestCase.java:124)
	at junit.framework.TestSuite.runTest(TestSuite.java:232)
	at junit.framework.TestSuite.run(TestSuite.java:227)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:83)
	at org.apache.maven.surefire.junit4.JUnit4TestSet.execute(JUnit4TestSet.java:62)
	at org.apache.maven.surefire.suite.AbstractDirectoryTestSuite.executeTestSet(AbstractDirectoryTestSuite.java:140)
	at org.apache.maven.surefire.suite.AbstractDirectoryTestSuite.execute(AbstractDirectoryTestSuite.java:127)
	at org.apache.maven.surefire.Surefire.run(Surefire.java:177)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.apache.maven.surefire.booter.SurefireBooter.runSuitesInProcess(SurefireBooter.java:345)
	at org.apache.maven.surefire.booter.SurefireBooter.main(SurefireBooter.java:1009)
----------------- before compilation of string resource (string input) (has_errors=false] -----------------
ERROR: line 3, column 1: .equ value3 value1
                         ^ Equation 'value3' has circular dependency: value3 <-> value1 <-> value2 <-> value3
----------------- before compilation of string resource (string input) (has_errors=false] -----------------
ERROR: line 2, column 1: .equ value2 value1
                         ^ Equation 'value2' has circular dependency: value2 <-> value1 <-> value2
----------------- before compilation of string resource (string input) (has_errors=false] -----------------
----------------- before compilation of specsample.dasm16 (has_errors=false] -----------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:09 min
[INFO] Finished at: 2018-02-19T23:41:22+07:00
[INFO] Final Memory: 22M/73M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.4.3:test (default-test) on project jasm16: There are test failures.
[ERROR] 
[ERROR] Please refer to /home/denizzz/Dev/DCPU16_stuff/jASM_16/target/surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```

**Comment by toby1984** [comment]
Sorry but unless you have a patch (or Notch changed his mind and decided to make the game) I'm not going to spend time on this. Besides, reporting a bug without describing your environment (which operating system,which JDK, JDK version,Maven version etc.) is not helpful.

**Comment by denizzzka** [comment]
> describing your environment (which operating system,which JDK, JDK version,Maven version etc.) 

Sorry. OS Debian Jessie. How to get another info? I am isn't know how to use Java environment at all, tried to start 'jre' and 'maven' - java binaries isn't OS executables or isn't in PATH dirs.
